
export const REQUEST_API_ITEM = `REQUEST_API_ITEM`;
export const SUCCESS_API_ITEM_ALBUMs = `SUCCESS_API_ITEM_ALBUMs`;
export const SUCCESS_API_ITEM_POSTs = `SUCCESS_API_ITEM_POSTs`;
export const SUCCESS_API_ITEM_PHOTOs = `SUCCESS_API_ITEM_PHOTOs`;