
export const REQUEST_API_ALBUMS = `REQUEST_API_ALBUMS`;
export const SUCCESS_API_ALBUMS = `SUCCESS_API_ALBUMS`;
export const REQUEST_API_PHOTOS = `REQUEST_API_PHOTOS`;
export const SUCCESS_API_PHOTOS = `SUCCESS_API_PHOTOS`;
